### ISSUE TITLE
How can I implement this on the BCH Testnet?

### ISSUE THREAD

**Issue by BCHTester** [SpendBCH/bch-stresstest-web#3]
I would like to know how can I implement this to the BCH testnet.

https://docs.google.com/spreadsheets/d/1Wg2ciYk7efDFpUD9qIz2Q9-Qp4H8i0Io8ThdDbGdyPU/edit#gid=299033565

**Comment by SpendBCH** [comment]
Testnet is supported but there are some considerations depending on what you want to test.

It is designed for many users to send a few thousand transactions each.
You can change the network here: https://github.com/SpendBCH/bch-stresstest-web/blob/master/public/index.html#L29

When testnet is enabled larger fees are used, and there may still be an insight bug on testnet that often reports a transaction as having 0 confirmations regardless of actual number.

Please join the BITBOX discord and add some additional information if you can: https://discord.gg/QNdVyJB
